---
- debug: msg="{{ manageiq.api_url }}/api/{{ manageiq.service }}/vms"
  ignore_errors: true

- name: Get VM from CF service
  uri:
    url: "{{ manageiq.api_url }}/api/{{ manageiq.service }}/vms"
    method: GET
    validate_certs: false
    headers:
      X-Auth-Token: "{{ manageiq.api_token }}"
      Content-Type: "application/json"
    status_code: 200
  register: get_service_vms_output

- debug: var=get_service_vms_output.json.resources[0]
  when: verbose

- name: Set fact 
  set_fact:
    vm_hrefs: get_service_vms_output.json.resources[0]

- debug: var="{{ vm_hrefs }}"
  when: verbose

- name: Get CF VM from service VM href
  uri:
    url: "{{ item.href }}"
    method: GET
    body:
      action: refresh
    body_format: json
    validate_certs: false
    headers:
      X-Auth-Token: "{{ manageiq.api_token }}"
      Content-Type: "application/json"
    status_code: 200
  register: get_vm_output
  with_items: "{{ get_service_vms_output.results }}"

- debug: var=get_vm_output
  when: verbose

- name: Assign CF tag to VM
  uri:
    url: "{{ item.href }}/tags"
    method: POST
    body_format: json
    body:
      action: assign
      resources: 
        - category: "{{ category }}"
          name: "{{ tag }}"
    validate_certs: false
    headers:
      X-Auth-Token: "{{ manageiq.api_token }}"
      Content-Type: "application/json"
    status_code: 200
  register: assign_tag_output
  with_items: "{{ get_vm_output.results }}"

- debug: var=assign_tag_output
  when: verbose  

