---
- name: Lookup CloudForms VM via uid_ems
  uri:
    url: "{{ manageiq.api_url }}/api/vms?filter[]=uid_ems={{ item.id }}&expand=resources"
    method: GET
    body:
      action: refresh
    body_format: json
    validate_certs: False
    headers:
      X-Auth-Token: "{{ manageiq.api_token }}"
      Content-Type: "application/json"
    status_code: 200
  register: lookup_output
  with_items: "{{ vms.instances }}"

- debug: var=lookup_output.results
  when: verbose

- debug: var=item.json.resources[0].href
  with_items: "{{ lookup_output.results }}"
  when: verbose


- name: Get CF VM from service VM href
  uri:
    url: "{{ item.href }}"
    method: GET
    body:
    body_format: json
    validate_certs: false
    headers:
      X-Auth-Token: "{{ manageiq.api_token }}"
      Content-Type: "application/json"
    status_code: 200
  register: get_vm_output
  with_items: "{{ vm_hrefs }}"

- debug: var=get_vm_output
  when: verbose

- name: Assign CF tag to VM
  uri:
    url: "{{ item.href }}/tags"
    method: POST
    body_format: json
    body:
      action: assign
      resources: 
        - category: "{{ category }}"
          name: "{{ tag }}"
    validate_certs: false
    headers:
      X-Auth-Token: "{{ manageiq.api_token }}"
      Content-Type: "application/json"
    status_code: 200
  register: assign_tag_output
  with_items: "{{ get_vm_output.results }}"

- debug: var=assign_tag_output
  when: verbose  

