---
- name: cloudforms_add_vm_to_service | Lookup CloudForms VM href
  uri:
    url: "{{ manageiq.api_url }}/api/vms?filter[]=name={{ item.id }}&expand=resources"
    method: GET
    body:
      action: refresh
    body_format: json
    validate_certs: False
    headers:
      X-Auth-Token: "{{ manageiq.api_token }}"
      Content-Type: "application/json"
    status_code: 200
  register: lookup_output
  with_items: "{{ vms.instances }}"

- name: cloudforms_add_vm_to_service | Set the Service URL
  set_fact:
    svc_url: "/api/{{ manageiq.service }}"

- debug: var=svc_url

- name: cloudforms_add_vm_to_service | Initialize an empty list for vms
  set_fact:
    vms: []

- name: cloudforms_add_vm_to_service | Append resource href to vms list
  set_fact:
    vms: "{{ vms }} + [ { 'href': svc_url, 'resource': { 'href': '/api/vms/{{ item.json.resources[0].id }}' } } ]"
  with_items: "{{ lookup_output.results }}"

- debug: var=vms

- name: cloudforms_add_vm_to_service | Add vms to the service
  uri:
    url: "{{ manageiq.api_url }}/api/services"
    method: POST
    body_format: json
    body:
      action: add_resource
      resources: "{{ vms }}"
    validate_certs: False
    headers:
      X-Auth-Token: "{{ manageiq.api_token }}"
      Content-Type: "application/json"
    status_code: 200
  register: add_output

- debug: var=add_output.json.results[0].success

- name: cloudforms_add_vm_to_service | Check if the VM was successfully attached to service
  fail: msg="{{ add_output.json.results[0].message }}"
  when: add_output.json.results[0].success == false