---
- name: Assign tag to CloudForms service "{{ category }}:{{ tag }}"
  uri:
    url: "{{ manageiq.api_url }}/api/{{ manageiq.service }}/tags"
    method: POST
    body_format: json
    body:
      action: assign
      resources: 
        - category: "{{ category }}"
          name: "{{ tag }}"
    validate_certs: false
    headers:
      X-Auth-Token: "{{ manageiq.api_token }}"
      Content-Type: "application/json"
    status_code: 200
  register: tag_service_output

- debug: var=tag_service_output