---
- name: AMAZON_VMPROVISIONING | MAIN | Launch ec2 instance
  local_action:
    module: ec2
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    key_name: "{{ key_name }}"
    group_id: "{{ group_id }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    vpc_subnet_id: "{{ vpc_subnet_id | random }}"
    region: "{{ region }}"
    instance_tags: "{{ instance_tags }}"
    assign_public_ip: "{{ assign_public_ip }}"
    wait: "{{ wait }}"
    count: "{{ count }}"
    volumes:
      - device_name: "{{ device_name }}"
        volume_size: "{{ volume_size }}"
        delete_on_termination: "{{ delete_on_termination }}"
    user_data: |
      #cloud-config
  register: ec2_vms

- debug: var=item
  with_items: "{{ ec2_vms.instances }}"

- name: AMAZON_VMPROVISIONING | MAIN | Wait for SSH
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  with_items: "{{ ec2_vms.instances }}"  

- name: AMAZON_VMPROVISIONING | MAIN | Set the Service URL
  set_fact:
    svc_url: "/api/{{ manageiq.service }}"
