- name: amazon_provisioning | main.yml | Launch ec2 instance(s)
    module: ec2
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      key_name: "{{ key_name }}"
      group_id: "{{ group_id }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image }}"
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      region: "{{ region }}"
      instance_tags: "{{ instance_tags }}"
      assign_public_ip: "{{ assign_public_ip }}"
      wait: "{{ wait }}"
      count: "{{ count }}"
      volumes:
      - device_name: "{{ device_name }}"
        volume_size: "{{ volume_size }}"
        delete_on_termination: "{{ delete_on_termination }}"
    register: ec2

- debug: var=item
  with_items: "{{ ec2.instances }}"

- name: amazon_provisioning | main.yml | wait for SSH
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  with_items: "{{ ec2.instances }}"  
  when: "{{ wair_for_ssh }}"

