---
- name: cloudforms_refresh_provider | Set the provider URL
  set_fact:
    provider_url: "{{ manageiq.api_url }}/api/providers/{{ provider_id }}"

- debug: var=provider_url

- name: cloudforms_refresh_provider | Refresh provider
  uri:
    url: "{{ provider_url }}"
    method: POST
    body:
      action: refresh
    body_format: json
    validate_certs: false
    headers:
      X-Auth-Token: "{{ manageiq.api_token }}"
      Content-Type: "application/json"
    status_code: 200
  register: refresh_output

- name: cloudforms_refresh_provider | Set the task href
  set_fact:
    task_url: "{{ refresh_output.json.task_href}}"

- debug: var=task_url

- name: cloudforms_refresh_provider | Wait for the provider refresh to end
  uri:
    url: "{{ task_url }}"
    method: GET
    validate_certs: false
    headers:
      X-Auth-Token: "{{ manageiq.api_token }}"
      Content-Type: "application/json"
    status_code: 200
  register: refresh_output
  until: refresh_output.json.state == 'Finished' or refresh_output.json.status == 'Error'
  failed_when: refresh_output.json.status == 'Error'
  retries: "{{ max_retries }}"
  delay: "{{ retry_interval }}"