---
- name: Provision Amazon EC2 Instance
  hosts: all
  gather_facts: false

  pre_tasks:
    - name: logging manageiq object
      debug: var=manageiq
      when: manageiq is defined
      
  roles:
    - { role: amazon_vmprovisioning, tags: [ 'appserver' ] }

- name: new task
  hosts: provisioned_ec2_instances
  gather_facts: true
  tasks:
    - ping:
