---
- name: Provision Amazon EC2 Instance
  hosts: localhost
  gather_facts: false

  pre_tasks:
    - name: logging manageiq object
      debug: var=manageiq
      when: manageiq is defined
      
  roles:
    - role: amazon_vmprovisioning
      tags: 
        - appserver

    - role: cloudforms_refresh_provider
      when: provider_id is defined and manageiq is defined

    - role: cloudforms_add_vm_to_service
      category: lifecycle
      tag: retire_full
      when: vms is defined and manageiq is defined

    - role: cloudforms_tag_service
      category: lifecycle
      tag: retire_full
      when: manageiq is defined

- name: Test SSH
  hosts: ec2_hosts
  become: true

  roles:
    - role: testssh
