---
- name: Provision Amazon EC2 Instance
  hosts: all
  gather_facts: false

  pre_tasks:
    - name: logging manageiq object
      debug: var=manageiq
      when: manageiq is defined
      
  roles:
    - role: amazon_vmprovisioning
      tags: [ 'appserver' ] 

    - role: cloudforms_add_vm_to_service
      when: manageiq is defined 

