---
- name: Provision Amazon EC2 Instance
  hosts: localhost
  gather_facts: false
      
  roles:
    - role: cloudforms_preprovision
      when: manageiq is defined

    - role: amazon_vmprovisioning
      tags: 
        - appserver

    - role: cloudforms_refresh_provider
      when: provider_id is defined and manageiq is defined

    - role: cloudforms_postprovision
      category: lifecycle
      tag: retire_full
      when: vms is defined and manageiq is defined

- name: Test SSH
  hosts: ec2_hosts
  become: true

  roles:
    - role: testssh
